export {movesSelector} from './moves.selector.js'
export {squaresSelector} from './squares.selector.js'
export {statusSelector} from './status.selector.js'
export {winnerSelector} from './winner.selector.js'
export {playerSelector} from './player.selector.js'